import * as fs from 'fs';

let tsFile = fs.readFileSync('src/data/applyTranslations.ts', 'utf8');

const newEn = `
    stepAbout: "ABOUT YOU",
    stepProject: "YOUR PROJECT",
    stepQuestions: "QUICK QUESTIONS",
    stepPuzzles: "SCIENCE PUZZLES",
    stepStatement: "PERSONAL STATEMENT",
    tellUsWho: "Tell us who you are.",
    justBasics: "Just the basics. No pressure — this is just so we know how to reach you.",
    namePlaceholder: "As it appears on your school ID",
    agePlaceholder: "e.g. 16",
    selectPlaceholder: "Select...",
    cityPlaceholder: "City",
    schoolPlaceholder: "Full official name",
    emailPlaceholder: "You'll hear from us here",
    phoneLabel: "Phone number",
    yourProjectTitle: "Your project.",
    yourProjectDesc: "Tell us what you built, studied, or discovered. The abstract is the most important thing here — take your time with it.",
    projectTitlePlaceholder: "Keep it clear — no need to be dramatic",
    individualOrTeam: "Individual or team?",
    abstractLimits: "up to 300 words",
    abstractPlaceholder: "Describe your project — the question you asked, how you approached it, what you found, and why it matters. Write it so a smart person outside your field can follow it.",
    uploadPdf: "Upload PDF or presentation",
    viewUploaded: "View uploaded file",
    quickQuestionsTitle: "A few quick questions.",
    shortAnswers: "Short answers are fine here.",
    travelSupportYes: "Yes",
    travelSupportNo: "No",
    competedYes: "Yes",
    competedNo: "No",
    puzzlesTitle: "Three problems.",
    puzzlesDesc: "These are not knowledge tests. We're not checking your textbook. We want to see how you reason — how you break things apart, ask questions, and think under uncertainty. Write however feels natural.",
    problem1Req: "PROBLEM 1 — OPTIONAL",
    clusterTitle: "The Cluster",
    clusterP1: "A rural school of 200 students suddenly sees 12 cases of severe headaches in one week — all from the same classroom. No one is hospitalized, but the pattern is clear. You're asked to investigate.",
    clusterP2: "List the first three things you would look into, and explain your reasoning for each. There is no single right answer — we're interested in how you think.",
    writeFreely: "Write freely. No format required.",
    typeAnswer: "Type your answer here...",
    problem2Req: "PROBLEM 2 — OPTIONAL",
    liquidTitle: "The Unknown Liquid",
    liquidP1: "You're handed 50 ml of a clear, odorless liquid. You cannot taste it. You have access to a standard school lab.",
    liquidP2: "Describe how you would determine whether it is pure water. Walk us through your steps and why you chose them.",
    problem3Opt: "PROBLEM 3 — OPTIONAL",
    greenhouseTitle: "The Greenhouse",
    greenhouseP1: "A student notices that their tomato plants grow taller when classical music plays in the greenhouse. After two weeks, they write in their notebook: \\"Music helps plant growth.\\"",
    greenhouseP2: "What — if anything — is wrong with that conclusion? And if you wanted to test it properly, how would you design the study?",
    statementTitleH2: "Personal statement.",
    statementDesc: "This is your chance to say something true. You don't need to answer every question below — they're prompts, not a checklist. Pick whatever feels most honest and write to that. One strong paragraph beats five generic ones.",
    statementQ1: "How would you describe yourself as a researcher or thinker? What makes the way you approach problems yours?",
    statementQ2: "Walk us through your project — not just what it is, but how you actually built it. What worked, what didn't?",
    statementQ3: "Has anyone — a teacher, a mentor, a book, or even a failure — changed the way you see your field?",
    statementQ4: "What's a question you can't stop thinking about, even outside your project?",
    statementQ5: "Was there a moment you almost gave up? What kept you going?",
    statementQ6: "If you could change one thing about how science is taught or done in your country, what would it be?",
    statementQ7: "What do you hope to take away from RSEF — not the award, but the experience?",
    statementPlaceholder: "Write in whatever language feels most natural to you. Uzbek or English, both are welcome.",
    beHonest: "Be honest. Be yourself.",
    backBtn: "Back",
    continueBtn: "Continue",
    submittedNote: "Your application has been submitted.",
    words: "words",
    stepXOf5: "STEP {step} OF 5 — {stepTitle}"
`;

const newUz = `
    stepAbout: "O'ZINGIZ HAQINGIZDA",
    stepProject: "LOYIHANGIZ",
    stepQuestions: "QISQA SAVOLLAR",
    stepPuzzles: "MANTIQIY SAVOLLAR",
    stepStatement: "SHAXSIY BAYONOT",
    tellUsWho: "O'zingiz haqingizda gapirib bering.",
    justBasics: "Shunchaki asosiy ma'lumotlar. Siz bilan qanday bog'lanishni bilishimiz uchun.",
    namePlaceholder: "Maktab guvohnomasida qanday yozilgan bo'lsa shunday",
    agePlaceholder: "masalan, 16",
    selectPlaceholder: "Tanlang...",
    cityPlaceholder: "Shahar",
    schoolPlaceholder: "To'liq rasmiy nomi",
    emailPlaceholder: "Sizga shu orqali xabar yuboramiz",
    phoneLabel: "Telefon raqami",
    yourProjectTitle: "Sizning loyihangiz.",
    yourProjectDesc: "Nima qurganingizni, o'rganganingizni yoki kashf etganingizni bizga ayting. Annotatsiya - bu yerdagi eng muhim qism, bunga yetarlicha vaqt ajrating.",
    projectTitlePlaceholder: "Aniq va lo'nda yozing",
    individualOrTeam: "Yakka yoki jamoa?",
    abstractLimits: "300 so'zgacha",
    abstractPlaceholder: "Loyihangizni ta'riflang — qanday savol qo'ydingiz, qanday yondashdingiz, nima topdingiz va nima uchun bu muhim. O'z sohangizdan tashqaridagi aqlli odam ham tushuna oladigan qilib yozing.",
    uploadPdf: "PDF yoki taqdimotni yuklang",
    viewUploaded: "Yuklangan faylni ko'rish",
    quickQuestionsTitle: "Bir nechta qisqa savollar.",
    shortAnswers: "Qisqa javoblar yetarli.",
    travelSupportYes: "Ha",
    travelSupportNo: "Yo'q",
    competedYes: "Ha",
    competedNo: "Yo'q",
    puzzlesTitle: "Uchta masala.",
    puzzlesDesc: "Bular bilim bo'yicha testlar emas. Biz sizning darslikdagi bilimlaringizni tekshirmaymiz. Biz siz qanday fikrlashingizni — qanday qilib narsalarni tahlil qilishingizni, savollar berish va noaniq holatlarda qanday o'ylashingizni ko'rishni xohlaymiz. O'zingizga qulay tilda erkin yozing.",
    problem1Req: "1-MASALA — IXTIYORIY",
    clusterTitle: "Klaster",
    clusterP1: "200 ta talaba tahsil oladigan qishloq maktabida bir hafta ichida aynan bitta sinfdagi 12 nafar o'quvchida kuchli bosh og'rig'i paydo bo'ldi. Hech kim kasalxonaga yotqizilmagan, ammo qonuniyat o'xshash. Sizga bu bo'yicha tekshiruv olib borish topshirildi.",
    clusterP2: "Bunday vaziyatda e'tibor qaratadigan birinchi uchta narsani sanab o'ting va ularning har biriga nima uchun e'tibor berishingizni izohlang. Yagona to'g'ri javob yo'q - biz siz qanday fikrlashingiz bilan qiziqamiz.",
    writeFreely: "Erkin yozing. Maxsus format talab qilinmaydi.",
    typeAnswer: "Javobingizni bu yerga yozing...",
    problem2Req: "2-MASALA — IXTIYORIY",
    liquidTitle: "Noma'lum suyuqlik",
    liquidP1: "Sizga 50 ml tiniq, hidsiz suyuqlik berildi. Siz uni tatib ko'rmasligingiz kerak. Standart maktab laboratoriyasiga kirish imkoni mavjud.",
    liquidP2: "Suyuqlik toza suv ekanligini qanday aniqlashingizni tasvirlang. Barcha qadamlarni tushuntiring va nima uchun ularni tanlaganingizni yozing.",
    problem3Opt: "3-MASALA — IXTIYORIY",
    greenhouseTitle: "Issiqxona",
    greenhouseP1: "Bir o'quvchi issiqxonada mumtoz musiqa chalinganda pomidor o'simliklarining uzunroq o'sayotganini ko'rdi. Ikki haftadan so'ng uni quyidagicha xulosani yozdi: \\"Musiqa o'simliklarning o'sishiga yordam beradi\\".",
    greenhouseP2: "Bu xulosaning nimasi xato (agar shunday bo'lsa)? Va agar xulosani to'g'ri tekshirishni xohlasangiz, tadqiqotni qanday loyihalashtirgan bo'lar edingiz?",
    statementTitleH2: "Shaxsiy bayonot.",
    statementDesc: "Bu haqiqatni aytish uchun imkoniyatingiz. Quyidagi hamma savolga albatta qat'iy javob berishingiz shart emas — ular ro'yxat emas, shunchaki maslahatlar. O'zingizga ma'qulini tanlab, eng rost deb bilganingizdek yozing. Beshta yuzaki xatboshidan bitta kuchli va samimiy xatboshi afzalroq.",
    statementQ1: "Tadqiqotchi yoki mutafakkir sifatida o'zingizni qanday ta'riflaysiz? Muammolarga yondashuvingizning o'ziga xosligi nimada?",
    statementQ2: "Bizga loyihangiz bo'yicha gapirib bering - faqat nima ekanligini emas, balki uni qanday yaratganingiz haqida. Nimasi o'xshadi, nimasi o'xshamadi?",
    statementQ3: "Sohangizga bo'lgan qarashingizni kimdir yoxud nimanir hisobiga o'zgartirdimi - biron bir ustoz, murabbiy, kitob yoki ehtimol xatolar?",
    statementQ4: "Loyiha doirasida bo'lmasa-da, doim fikringizni band etgan, to'xtovsiz o'ylantiradigan narsa/savol bormi?",
    statementQ5: "Sizda deyarli taslim bo'lay degan paytlar ham bo'lganmi? Nega bunday vaziyatda ham chekinmagansiz?",
    statementQ6: "Mamlakatingizdagi fanga oid sharoitda biror nimani o'zgartira olganda u nima bo'lardi?",
    statementQ7: "RSEF dan (sovrindan tashqari) nimalarni olishni/o'rganishni umid qilyapsiz?",
    statementPlaceholder: "O'zingizga qulay bo'lgan har qanday tilda yozing. O'zbek yoki ingliz tillarida - ikkalasi ham qabul qilinadi.",
    beHonest: "Samimiy bo'ling.",
    backBtn: "Orqaga",
    continueBtn: "Davom etish",
    submittedNote: "Arizangiz yuborildi.",
    words: "so'z",
    stepXOf5: "BOSQICH {step} / 5 — {stepTitle}"
`;

const newRu = `
    stepAbout: "О ВАС",
    stepProject: "ВАШ ПРОЕКТ",
    stepQuestions: "БЫСТРЫЕ ВОПРОСЫ",
    stepPuzzles: "ЛОГИЧЕСКИЕ ЗАДАЧИ",
    stepStatement: "ЛИЧНОЕ ЗАЯВЛЕНИЕ",
    tellUsWho: "Расскажите нам о себе.",
    justBasics: "Только основное. Без давления — это всего лишь для того, чтобы мы знали, как с вами связаться.",
    namePlaceholder: "Как написано в справке или паспорте",
    agePlaceholder: "например, 16",
    selectPlaceholder: "Выберите...",
    cityPlaceholder: "Город",
    schoolPlaceholder: "Полное официальное название",
    emailPlaceholder: "Мы свяжемся с вами здесь",
    phoneLabel: "Номер телефона",
    yourProjectTitle: "Ваш проект.",
    yourProjectDesc: "Расскажите, что вы построили, изучили или открыли. Аннотация здесь — самое важное, уделите ей достаточно времени.",
    projectTitlePlaceholder: "Коротко и ясно — без лишнего пафоса",
    individualOrTeam: "Индивидуально или команда?",
    abstractLimits: "до 300 слов",
    abstractPlaceholder: "Опишите ваш проект — вопрос, который вы задали, как вы к нему подошли, что вы нашли и почему это важно. Напишите так, чтобы умный человек за пределами вашей области смог понять.",
    uploadPdf: "Загрузить PDF или презентацию",
    viewUploaded: "Просмотреть загруженный файл",
    quickQuestionsTitle: "Несколько коротких вопросов.",
    shortAnswers: "Здесь достаточно коротких ответов.",
    travelSupportYes: "Да",
    travelSupportNo: "Нет",
    competedYes: "Да",
    competedNo: "Нет",
    puzzlesTitle: "Три задачи.",
    puzzlesDesc: "Это не тесты на знания. Мы не проверяем ваш учебник. Мы хотим увидеть, как вы рассуждаете — как разбиваете вещи на части, задаете вопросы и мыслите в условиях неопределенности. Пишите так, как вам удобно.",
    problem1Req: "ЗАДАЧА 1 — НЕОБЯЗАТЕЛЬНО",
    clusterTitle: "Кластер",
    clusterP1: "В сельской школе на 200 учеников за одну неделю внезапно зафиксировано 12 случаев сильных головных болей — все из одного класса. Никто не госпитализирован, но закономерность очевидна. Вам поручено расследовать это.",
    clusterP2: "Перечислите три вещи, которые вы проверили бы в первую очередь, и объясните свои рассуждения по каждой. Правильного ответа нет — нам интересно, как вы мыслите.",
    writeFreely: "Пишите свободно. Формат не требуется.",
    typeAnswer: "Введите ваш ответ здесь...",
    problem2Req: "ЗАДАЧА 2 — НЕОБЯЗАТЕЛЬНО",
    liquidTitle: "Hеизвестная жидкость",
    liquidP1: "Вам дают 50 мл прозрачной жидкости без запаха. Вы не можете ее попробовать. У вас есть доступ к стандартной школьной лаборатории.",
    liquidP2: "Опишите, как бы вы определили, является ли это чистой водой. Проведите нас по своим шагам и почему вы их выбрали.",
    problem3Opt: "ЗАДАЧА 3 — НЕОБЯЗАТЕЛЬНО",
    greenhouseTitle: "Теплица",
    greenhouseP1: "Студент замечает, что его кусты помидоров растут выше, если в теплице играет классическая музыка. Через две недели он пишет в своей тетради: \\"Музыка способствует росту растений\\".",
    greenhouseP2: "Что — если вообще что-то — не так с этим выводом? И если бы вы хотели правильно это проверить, как бы вы спланировали исследование?",
    statementTitleH2: "Личное заявление.",
    statementDesc: "Это ваш шанс сказать что-то настоящее. Не обязательно отвечать на каждый вопрос ниже — это подсказки, а не контрольный список. Выберите то, что кажется самым честным, и напишите об этом. Один сильный абзац лучше пяти шаблонных.",
    statementQ1: "Как бы вы описали себя как исследователя или мыслителя? Что делает ваш подход к проблемам уникальным?",
    statementQ2: "Расскажите нам о своем проекте — не только о том, что это такое, но и как вы его на самом деле создали. Что сработало, а что нет?",
    statementQ3: "Кто-нибудь — учитель, наставник, книга или даже неудача — изменил ваше отношение к вашей области?",
    statementQ4: "Какой вопрос, о котором вы не можете перестать думать, даже за пределами вашего проекта?",
    statementQ5: "Был ли момент, когда вы почти сдались? Что заставило вас двигаться дальше?",
    statementQ6: "Если бы вы могли изменить что-то одно в том, как преподается или делается наука в вашей стране, что бы это было?",
    statementQ7: "Что вы надеетесь получить от RSEF — не награду, а опыт?",
    statementPlaceholder: "Пишите на любом языке, который кажется вам наиболее естественным. Узбекский (кириллица, латиница) или английский, оба приветствуются.",
    beHonest: "Будьте собой.",
    backBtn: "Назад",
    continueBtn: "Продолжить",
    submittedNote: "Ваша заявка отправлена.",
    words: "слов",
    stepXOf5: "ШАГ {step} ИЗ 5 — {stepTitle}"
`;

tsFile = tsFile.replace(/uploading:\s*"Uploading file..."\n\s*}/g, 'uploading: "Uploading file...",\n' + newEn + '\\n    }');
tsFile = tsFile.replace(/uploading:\s*"Fayl yuklanmoqda..."\n\s*}/g, 'uploading: "Fayl yuklanmoqda...",\n' + newUz + '\\n    }');
tsFile = tsFile.replace(/uploading:\s*"Загрузка файла..."\n\s*}/g, 'uploading: "Загрузка файла...",\n' + newRu + '\\n    }');

fs.writeFileSync('src/data/applyTranslations.ts', tsFile);
